language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
before_script:
- composer install --dev
script: vendor/bin/phpunit
matrix:
  allow_failures:
  - php: 5.6
  fast_finish: true
env:
  matrix:
  - secure: VyCVYebILLYIHzPMASb/1YPDBl/2HgoqS0gv6/5zSAOIcAuUkxtnLUEV1CEdpSC24iVfuflNlGzp2bnc1hr0MC3tpaNVYQgzz0RlsJLRgLIm66xBjVBlUsPRrVXvverE6CHd0wp1P/d8jd1Iv6E+M9JvMn6ERZxDvrYNQraMp9Q=
