language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
before_script:
- composer install --dev
script: vendor/bin/phpunit
matrix:
  allow_failures:
  - php: 5.6
  fast_finish: true
env:
  matrix:
  - secure: eA9gjNhFN3wke7iYSZkIxITl6CxlsYSWYC+IYgzBYTcLkqlkD13TtTbB4gSKA6ORm/kimvN+9btcPrCwPoxYHR44T+NZtAOtqNOaGZJBj/iArMd6FZxmMhjGi2YzlXTYer/e1bodV687V3rysZc6TeFn8M9yr6xkDksyVmM2mjg=
